spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .html
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: postgres
server:
  servlet:
    context-path: /